"""I8 — Advanced DBs assignment.

A small Flask API that serves Seattle "Where Does It Go?" items from this
repo's existing ``data/items.json`` as a NoSQL-style document store. The
file is loaded once at server startup into an in-memory dictionary keyed
by ``item_id``, and the endpoints query that store.

Built on the I7 individual API using the same portable JSON structure
generated by ``portable_waste_sorting.ipynb`` at the repo root.
"""

from collections import Counter
from flask import Flask, jsonify, request
import json
import os

app = Flask(__name__)

DATA_FILE = os.path.join(os.path.dirname(__file__), "..", "data", "items.json")

VALID_STREAMS = {
    "garbage", "recycling", "compost", "donate",
    "dropoff", "hazardous", "special",
}


def load_data(path):
    with open(path) as f:
        return json.load(f)


# --- Load the JSON "NoSQL" store once at startup -----------------------------
DATA = load_data(DATA_FILE)
METADATA = DATA["metadata"]
ITEMS = DATA["items"]
CATEGORY_TREE = DATA.get("category_tree", [])
ITEMS_BY_ID = {i["item_id"]: i for i in ITEMS}


def to_summary(item):
    """Compact view of an item for list responses."""
    return {
        "item_id": item["item_id"],
        "item_name": item["item_name"],
        "disposal_streams": item.get("disposal_streams", []),
        "category_path": item.get("category_path", []),
    }


@app.route("/")
def info():
    return jsonify({
        "name": "Which Bin API (I8)",
        "description": (
            "Serves Seattle 'Where Does It Go?' waste-sorting items from a "
            "JSON document store. Built on the I7 API for the group project's "
            "portable waste-sorting information structure."
        ),
        "data_source": {
            "type": "static JSON file loaded at startup (NoSQL-style doc store)",
            "file": "data/items.json",
            "item_count": METADATA.get("item_count", len(ITEMS)),
            "source": METADATA.get("source"),
            "city_jurisdiction": METADATA.get("city_jurisdiction"),
        },
        "endpoints": [
            "GET /",
            "GET /items",
            "GET /items/<item_id>",
            "GET /search?q=&stream=&category=",
            "GET /streams",
            "GET /streams/<stream>",
            "GET /categories",
            "GET /categories/<name>",
            "GET /stats",
        ],
    })


@app.route("/items")
def all_items():
    """All items in summary form."""
    return jsonify({
        "count": len(ITEMS),
        "items": [to_summary(i) for i in ITEMS],
    })


@app.route("/items/<item_id>")
def item_by_id(item_id):
    """Full record for one item by item_id. 404 if not found."""
    item = ITEMS_BY_ID.get(item_id)
    if item is None:
        return jsonify({
            "error": "item not found",
            "item_id": item_id,
        }), 404
    return jsonify(item)


@app.route("/search")
def search():
    """Filter items by name/synonym query, disposal stream, and/or category.

    Query params (all optional, combined with AND):
      q        substring match on item_name or any synonym (case-insensitive)
      stream   disposal stream (e.g. compost, recycling, garbage)
      category top-level category name (e.g. "Plastic", "Food Packaging")
    """
    q = (request.args.get("q") or "").strip().lower()
    stream = (request.args.get("stream") or "").strip().lower()
    category = (request.args.get("category") or "").strip().lower()

    if not q and not stream and not category:
        return jsonify({
            "error": "provide at least one of q, stream, or category",
        }), 400

    if stream and stream not in VALID_STREAMS:
        return jsonify({
            "error": "invalid stream",
            "stream": stream,
            "valid_streams": sorted(VALID_STREAMS),
        }), 400

    results = []
    for i in ITEMS:
        if q:
            name = i["item_name"].lower()
            syns = [s.lower() for s in i.get("synonyms", [])]
            if q not in name and not any(q in s for s in syns):
                continue
        if stream and stream not in i.get("disposal_streams", []):
            continue
        if category:
            path = [p.lower() for p in i.get("category_path", [])]
            if category not in path:
                continue
        results.append(to_summary(i))

    return jsonify({
        "query": {"q": q or None, "stream": stream or None, "category": category or None},
        "count": len(results),
        "items": results,
    })


@app.route("/streams")
def streams_summary():
    """Counts of items per disposal stream."""
    counts = Counter()
    for i in ITEMS:
        for s in i.get("disposal_streams", []):
            counts[s] += 1
    return jsonify({"streams": dict(counts)})


@app.route("/streams/<stream>")
def items_by_stream(stream):
    """All items that include the given disposal stream."""
    s = stream.lower()
    if s not in VALID_STREAMS:
        return jsonify({
            "error": "invalid stream",
            "stream": stream,
            "valid_streams": sorted(VALID_STREAMS),
        }), 404
    matches = [to_summary(i) for i in ITEMS if s in i.get("disposal_streams", [])]
    return jsonify({"stream": s, "count": len(matches), "items": matches})


@app.route("/categories")
def categories():
    """Top-level category names with item counts."""
    counts = Counter()
    for i in ITEMS:
        if i.get("category_path"):
            counts[i["category_path"][0]] += 1
    return jsonify({
        "count": len(counts),
        "categories": [{"name": n, "item_count": c} for n, c in counts.most_common()],
    })


@app.route("/categories/<name>")
def items_by_category(name):
    """All items whose top-level category equals <name> (case-insensitive)."""
    target = name.lower()
    matches = [
        to_summary(i) for i in ITEMS
        if i.get("category_path") and i["category_path"][0].lower() == target
    ]
    if not matches:
        return jsonify({
            "error": "category not found or empty",
            "category": name,
        }), 404
    return jsonify({
        "category": name,
        "count": len(matches),
        "items": matches,
    })


@app.route("/stats")
def stats():
    """Summary statistics across the document store."""
    stream_counts = Counter()
    cat_counts = Counter()
    multi_stream = 0
    for i in ITEMS:
        streams = i.get("disposal_streams", [])
        for s in streams:
            stream_counts[s] += 1
        if len(streams) > 1:
            multi_stream += 1
        if i.get("category_path"):
            cat_counts[i["category_path"][0]] += 1
    return jsonify({
        "total_items": len(ITEMS),
        "items_with_multiple_streams": multi_stream,
        "stream_counts": dict(stream_counts),
        "top_categories": [
            {"name": n, "item_count": c}
            for n, c in cat_counts.most_common(5)
        ],
        "metadata": METADATA,
    })


@app.errorhandler(404)
def not_found(_e):
    return jsonify({"error": "route not found"}), 404


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=True)
